---

- name: Install and Start Nginix
  hosts: all
  become: yes

  tasks:
   - name: Install nginx
     apt:
      name: nginx
      state: present
   - name: Start nginx
     service:
      name: nginx
      state: started
